language: java

sudo: true

script: 
  - cd zeebe-aws-event-bridge-server
  - mvn --settings .maven-settings.xml clean package
  - cd ..

services:
  - docker

cache:
  directories:
    - $HOME/.m2
jdk:
  - openjdk11
os:
  - linux

branches:
  only:
    - master

after_success:
  - docker login -u _json_key -p "${GCR_JSON_KEY}" https://eu.gcr.io
  - docker build -t zeebe-aws-event-bridge-server ./zeebe-aws-event-bridge-server/
  - docker tag zeebe-aws-event-bridge-server eu.gcr.io/${GCP_PROJECT_NAME}/zeebe-aws-event-bridge-server
  - docker push eu.gcr.io/${GCP_PROJECT_NAME}/zeebe-aws-event-bridge-server
