spring:
  datasource.url: jdbc:h2:file:./camunda-h2-database
  h2.console.enabled: true
  jpa.hibernate.ddl-auto: update

camunda.bpm.admin-user:
  id: demo
  password: demo
  
aws:
  access_key_id: xxx
  secret_access_key: yyy