spring:
  datasource.url: jdbc:h2:file:./h2-db-zeebe-aws-event-bridge
  h2.console.enabled: true
  jpa.hibernate.ddl-auto: update

camunda.bpm:
  admin-user:
    id: demo
    password: demo
  webapp.index-redirect-enabled: false
  
aws:
  access_key_id: x
  secret_access_key: y